CREATE TABLE PERMISSION ( ID INT PRIMARY KEY AUTO_INCREMENT, PERMISSION_NAME VARCHAR(60) UNIQUE KEY NOT NULL);
CREATE TABLE ROLE (ID INT PRIMARY KEY AUTO_INCREMENT, ROLE_NAME VARCHAR(60) UNIQUE KEY NOT NULL);
CREATE TABLE ROLE_PERMISSION (ID INT PRIMARY KEY AUTO_INCREMENT, PERMISSION_ID INT,FOREIGN KEY(PERMISSION_ID) REFERENCES PERMISSION(ID),ROLE_ID INT,FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ID));

DESC PERMISSION;
DESC ROLE;
DESC ROLE_PERMISSION;


CREATE TABLE USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(1000) NOT NULL,
    EMAIL_ID VARCHAR(50) NOT NULL,
	MOBILE VARCHAR(20),
	COUNTRY VARCHAR(50),
	USER_TYPE VARCHAR(20));
	
	CREATE TABLE ROLE_USERS (ID INT PRIMARY KEY AUTO_INCREMENT, ROLE_ID INT,FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ID),
    USER_ID INT, FOREIGN KEY(USER_ID) REFERENCES USERS(ID));
    
	
DESC USERS;
DESC ROLE_USERS;


INSERT INTO PERMISSION (PERMISSION_NAME) VALUES ('view_permission');

INSERT INTO PERMISSION (PERMISSION_NAME) VALUES ('create_role');
INSERT INTO PERMISSION (PERMISSION_NAME) VALUES ('edit_role');
INSERT INTO PERMISSION (PERMISSION_NAME) VALUES ('view_role');
INSERT INTO PERMISSION (PERMISSION_NAME) VALUES ('delete_role');

INSERT INTO PERMISSION (PERMISSION_NAME) VALUES ('assign_permissions_to_role');
INSERT INTO PERMISSION (PERMISSION_NAME) VALUES ('view_permissions_by_role');

INSERT INTO PERMISSION (PERMISSION_NAME) VALUES ('create_users');
INSERT INTO PERMISSION (PERMISSION_NAME) VALUES ('edit_users');
INSERT INTO PERMISSION (PERMISSION_NAME) VALUES ('view_users');
INSERT INTO PERMISSION (PERMISSION_NAME) VALUES ('delete_users');

INSERT INTO PERMISSION (PERMISSION_NAME) VALUES ('assign_users_to_role');
INSERT INTO PERMISSION (PERMISSION_NAME) VALUES ('view_users_by_role');

INSERT INTO ROLE (ROLE_NAME) VALUES ('Administrator');

INSERT INTO ROLE_PERMISSION (ROLE_ID,PERMISSION_ID) VALUES (1, 1 );
INSERT INTO ROLE_PERMISSION (ROLE_ID,PERMISSION_ID) VALUES (1, 2 );
INSERT INTO ROLE_PERMISSION (ROLE_ID,PERMISSION_ID) VALUES (1, 3 );
INSERT INTO ROLE_PERMISSION (ROLE_ID,PERMISSION_ID) VALUES (1, 4 );
INSERT INTO ROLE_PERMISSION (ROLE_ID,PERMISSION_ID) VALUES (1, 5 );
INSERT INTO ROLE_PERMISSION (ROLE_ID,PERMISSION_ID) VALUES (1, 6 );
INSERT INTO ROLE_PERMISSION (ROLE_ID,PERMISSION_ID) VALUES (1, 7 );
INSERT INTO ROLE_PERMISSION (ROLE_ID,PERMISSION_ID) VALUES (1, 8 );
INSERT INTO ROLE_PERMISSION (ROLE_ID,PERMISSION_ID) VALUES (1, 9 );
INSERT INTO ROLE_PERMISSION (ROLE_ID,PERMISSION_ID) VALUES (1,10 );
INSERT INTO ROLE_PERMISSION (ROLE_ID,PERMISSION_ID) VALUES (1,11 );
INSERT INTO ROLE_PERMISSION (ROLE_ID,PERMISSION_ID) VALUES (1,12 );
INSERT INTO ROLE_PERMISSION (ROLE_ID,PERMISSION_ID) VALUES (1,13 );

INSERT INTO USERS (FIRST_NAME,LAST_NAME,EMAIL_ID,PASSWORD,MOBILE,COUNTRY,USER_TYPE) VALUES (
    'Kite','Danie','kite_d@gmail.com','$2a$10$RshVOc.2yV5hXKbQRGjhsu9io0qmzyZM5X.0UIP6HuZAmxZW5TEJu','+918505866586','USA','super_admin');
	
INSERT INTO USERS (FIRST_NAME,LAST_NAME,EMAIL_ID,PASSWORD,MOBILE,COUNTRY,USER_TYPE) VALUES (
 'William','John','william_j@gmail.com','$2a$10$RshVOc.2yV5hXKbQRGjhsu9io0qmzyZM5X.0UIP6HuZAmxZW5TEJu','+918505866588','USA','admin');
 
 INSERT INTO ROLE_USERS (ROLE_ID, USER_ID) VALUES (1, 2) ;
 
SELECT * FROM USERS WHERE EMAIL_ID = 'kite_d@gmail.com';
SELECT * FROM USERS WHERE EMAIL_ID = 'william_j@gmail.com';

SELECT p.PERMISSION_NAME FROM USERS u inner join ROLE_USERS r_u on r_u.USER_ID=u.ID
inner join ROLE r on r.ID = r_u.ROLE_ID
inner join ROLE_PERMISSION R_P on R_P.ROLE_ID = r.ID
inner join PERMISSION p on p.id = R_P.PERMISSION_ID
WHERE u.EMAIL_ID = 'william_j@gmail.com';


SELECT p.PERMISSION_NAME FROM USERS u inner join ROLE_USERS r_u on r_u.USER_ID=u.ID
inner join ROLE_PERMISSION R_P on R_P.ROLE_ID = r_u.ROLE_ID
inner join PERMISSION p on p.id = R_P.PERMISSION_ID
WHERE u.EMAIL_ID = 'william_j@gmail.com';
